services:
  mongodb:
    image: mongo:6
    container_name: shipfinex_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: shipfinex_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: shipfinex_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    restart: unless-stopped

volumes:
  mongo_data:
